import {
  Activity,
  Airplay,
  AlarmClock,
  AlertCircle,
  AlignCenter,
  Anchor,
  Aperture,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  Award,
  BarChart,
  Battery,
  Bell,
  Bluetooth,
  Book,
  Bookmark,
  Briefcase,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clipboard,
  Clock,
  Cloud,
  Code,
  Compass,
  Copy,
  CreditCard,
  Crop,
  Database,
  Delete,
  Download,
  Edit,
  Eye,
  File,
  Filter,
  Flag,
  Folder,
  Globe,
  Grid,
  Heart,
  HelpCircle,
  Home,
} from "lucide-react";
import React from "react";
export const icons = [
  { label: "activity", icon: React.createElement(Activity) },
  { label: "airplay", icon: React.createElement(Airplay) },
  { label: "alarm-clock", icon: React.createElement(AlarmClock) },
  { label: "alert-circle", icon: React.createElement(AlertCircle) },
  { label: "align-center", icon: React.createElement(AlignCenter) },
  { label: "anchor", icon: React.createElement(Anchor) },
  { label: "aperture", icon: React.createElement(Aperture) },
  { label: "archive", icon: React.createElement(Archive) },
  { label: "arrow-down", icon: React.createElement(ArrowDown) },
  { label: "arrow-left", icon: React.createElement(ArrowLeft) },
  { label: "arrow-right", icon: React.createElement(ArrowRight) },
  { label: "arrow-up", icon: React.createElement(ArrowUp) },
  { label: "at-sign", icon: React.createElement(AtSign) },
  { label: "award", icon: React.createElement(Award) },
  { label: "bar-chart", icon: React.createElement(BarChart) },
  { label: "battery", icon: React.createElement(Battery) },
  { label: "bell", icon: React.createElement(Bell) },
  { label: "bluetooth", icon: React.createElement(Bluetooth) },
  { label: "book", icon: React.createElement(Book) },
  { label: "bookmark", icon: React.createElement(Bookmark) },
  { label: "briefcase", icon: React.createElement(Briefcase) },
  { label: "calendar", icon: React.createElement(Calendar) },
  { label: "camera", icon: React.createElement(Camera) },
  { label: "check", icon: React.createElement(Check) },
  { label: "chevron-down", icon: React.createElement(ChevronDown) },
  { label: "chevron-left", icon: React.createElement(ChevronLeft) },
  { label: "chevron-right", icon: React.createElement(ChevronRight) },
  { label: "chevron-up", icon: React.createElement(ChevronUp) },
  { label: "clipboard", icon: React.createElement(Clipboard) },
  { label: "clock", icon: React.createElement(Clock) },
  { label: "cloud", icon: React.createElement(Cloud) },
  { label: "code", icon: React.createElement(Code) },
  { label: "compass", icon: React.createElement(Compass) },
  { label: "copy", icon: React.createElement(Copy) },
  { label: "credit-card", icon: React.createElement(CreditCard) },
  { label: "crop", icon: React.createElement(Crop) },
  { label: "database", icon: React.createElement(Database) },
  { label: "delete", icon: React.createElement(Delete) },
  { label: "download", icon: React.createElement(Download) },
  { label: "edit", icon: React.createElement(Edit) },
  { label: "eye", icon: React.createElement(Eye) },
  { label: "file", icon: React.createElement(File) },
  { label: "filter", icon: React.createElement(Filter) },
  { label: "flag", icon: React.createElement(Flag) },
  { label: "folder", icon: React.createElement(Folder) },
  { label: "globe", icon: React.createElement(Globe) },
  { label: "grid", icon: React.createElement(Grid) },
  { label: "heart", icon: React.createElement(Heart) },
  { label: "help-circle", icon: React.createElement(HelpCircle) },
  { label: "home", icon: React.createElement(Home) },
];
